### ISSUE TITLE
Error — It seems I cannot access this Framer prototype

### ISSUE THREAD

**Issue by didacus** [kysely/framer-modules#3]
I've tried to use this software with different prototypes without success. What am I doing wrong?

**Comment by ryokun6** [comment]
+1 to this problem

**Comment by kysely** [comment]
Hey, I'm really sorry about the inconvenience! You're getting this error because Framer Modules **app doesn't have `write` permissions for the prototype folder**.

Since I cannot replicate this behavior, I'd like to ask you to help me debug this:
- [:point_right: Download the special build](https://github.com/kysely/framer-modules/releases/tag/debug) I created for debugging this issue
- Open the downloaded app and try to open a prototype
- The following will happen:
    1. A window with the prototype path will pop up. **Please check and report** if the shown path to the prototype is correct.
    2. After the first popup, the same main error will occur; this time including more descriptive message. **Please report the error message here**.
   3. Unlike the production version of the app, this one will allow you to open the app even after the error. Please continue, **try to use it and report if there's any error occuring inside the app** (should display in a pink bar at the bottom). Or is it working properly? Can you install a module?

Try opening multiple prototypes (ideally from different partitions or parts of your disk). Is your disk encrypted? **Does this issue also happen when you open a prototype manually** (by dragging a prototype folder onto the app icon in menu bar)?

**Please return here and report as many information as possible**. The issue is “missing write permissions”, so if you can think of anything else regarding this, don't hesitate to also include these thoughts.

Here's a short template for reporting your results
```md
**The prototype path shown in the first popup is correct?** Yes or No

**The prototype path shown in the first popup is:** `please insert the specific path shown in the popup`

**Detailed error from the second window is:** `please insert the specific error shown in the popup`

**After closing all error windows, the app window was loaded:** Yes or No

**After loading the app, I did get some error in the pink bar at the bottom** Yes or No. If 'yes', please `include the error message` as well

**I was able to use the app (e.g. install a module):** Yes or No. If 'no', please describe the behavior or `include the error message you got`
```

**Comment by ryokun6** [comment]
Not sure if related, but macOS sandbox doesn't allow file access without
user interactions. You can call NSOpenPanel to open the files instead.
Dragging works fine

**Comment by ikbenivo** [comment]
**The prototype path shown in the first popup is correct?** 
Yes

**The prototype path shown in the first popup is:** `please insert the specific path shown in the popup` [sorry, didn't copy this]

**Detailed error from the second window is:** 
ENOENT: no such file or directory, access '/Users/me/Documents/Around Seven/simacan/Control%20Tower/prototype.framer'

**After closing all error windows, the app window was loaded:** 
Yes

**After loading the app, I did get some error in the pink bar at the bottom**  
Yes:  ENOENT: no such file or directory, scandir '/Users/me/Documents/Around Seven/simacan/Control%20Tower/prototype.framer/modules' 

**I was able to use the app (e.g. install a module):** 
No. No modules listed

**Comment by didacus** [comment]
**The prototype path shown in the first popup is correct?**
No. The prototype showed and the path do not exist.

**The prototype path shown in the first popup is:** 
/Users/diegooriani/Downloads/linkedLayers(1).framer 

**Detailed error from the second window is:**
The same access error again. You will however enter the app. ENOENT: no such file or directory, access '/Users/diegooriani/Downloads/linkedLayers (1).framer'

**After closing all error windows, the app window was loaded:**
Yes

**After loading the app, I did get some error in the pink bar at the bottom**
Yes: ENOENT: no such file or directory, scandir '/Users/diegooriani/Downloads/linkedLayers (1).framer'

**I was able to use the app (e.g. install a module):**
No.
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Users/diegooriani/Downloads/linkedLayers (1).framer/app.coffee'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at updateRequireCommand (/private/var/folders/v5/07nys15s27j8zpn2s_sxllzc0000gn/T/AppTranslocation/72F29DFF-32C1-445E-B9F2-A249EE4A44FF/d/Framer Modules.app/Contents/Resources/app.asar/app/core/prototype-actions/updateRequireCommand.js:81:36)
    at /private/var/folders/v5/07nys15s27j8zpn2s_sxllzc0000gn/T/AppTranslocation/72F29DFF-32C1-445E-B9F2-A249EE4A44FF/d/Framer Modules.app/Contents/Resources/app.asar/app/core/prototype-actions/installRemove.js:214:56
    at next (/private/var/folders/v5/07nys15s27j8zpn2s_sxllzc0000gn/T/AppTranslocation/72F29DFF-32C1-445E-B9F2-A249EE4A44FF/d/Framer Modules.app/Contents/Resources/app.asar/node_modules/rimraf/rimraf.js:74:7)
    at FSReqWrap.CB [as oncomplete] (/private/var/folders/v5/07nys15s27j8zpn2s_sxllzc0000gn/T/AppTranslocation/72F29DFF-32C1-445E-B9F2-A249EE4A44FF/d/Framer Modules.app/Contents/Resources/app.asar/node_modules/rimraf/rimraf.js:110:9)

**Comment by kysely** [comment]
Thank you guys for trying this out! Really appreciate it.

@ikbenivo @didacus Can you please also try opening a prototype manually and reporting whether or not that works? You can open manually via either **dragging the prototype onto the app icon in menubar** or by pressing <kbd>Cmd</kbd><kbd>O</kbd>

@ryokun6 Thanks for pointing that out, didn't know about this but it feels like the most probable option here. I don't have direct access to NS classes via Electron, but I believe NSOpenPanel is what's being called via Electron methods when you press <kbd>Cmd</kbd><kbd>O</kbd>. This however really disrupts the user experience of the app (the prototype is supposed to be loaded automatically)... Anyway, will look at it, maybe I can present that open dialog as an alternative in case of this error, which still makes the app much more useful.

**Comment by didacus** [comment]
**Manually opening a prototype**
It does work but there is a problem when the app window is no longer on focus. The app goes back to the default project that does not exist on my system.
[Video](https://cl.ly/3m2w2y3D3134)

**Comment by didacus** [comment]
Any progress with this issue?

**Comment by kysely** [comment]
@didacus Sorry, I haven't really worked on that. However, I just pushed some questions around Electron community and will try giving it more of my spare time. Thanks for the reminder.

**Comment by didacus** [comment]
@kysely Thanks. I really want to use this software. Please keep me updated.

**Comment by curious1n** [comment]
@kysely any updates? :)

**Comment by danniph** [comment]
i saw the same error. And now it is working after I removed the space inside my framer prototype file name, and the space inside the name of the folder. Hope this helps!

**Comment by darkostanimirovic** [comment]
I also have this error. Thanks @danniph for pointing me in the right direction – I renamed my prototype and moved to ~/Documents so that it's out of path containing spaces (like "Google Drive"). Now it's working.

**Comment by josephxbrick** [comment]
I was having the same problem, and indeed it was because some folder in the file's path had a space in its name. Thanks, @danniph!

**Comment by philworthy** [comment]
Hi I had same problem. Downloaded the debug app and it asked me to report the following:
ENOENT: no such file or directory, access '/Users/phil/Downloads/Form Element%20Symbols.framer'.

Note: Also seeing some visual bugs (not sure if related) in the header bar https://cl.ly/3Q1C41461e0k

Thanks!

**Comment by briandito** [comment]
Thanks @danniph –– @kysely check out her answer!
